[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
epaint = { workspace = true }
winit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
font-kit = { workspace = true }
owned_ttf_parser = { workspace = true }
crossbeam = { workspace = true }
windows = { workspace = true }
rfd = { workspace = true }
image = { workspace = true }
bytemuck = { workspace = true }
interprocess = { workspace = true }
